# Generated by Django 6.0.1 on 2026-01-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('color_principal', models.CharField(default='#22c55e', max_length=7)),
                ('tipografia', models.CharField(default="'Montserrat', sans-serif", max_length=100)),
                ('imagen_fondo', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
