# Generated by Django 6.0.1 on 2026-01-26 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cliente_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Cliente / Empresa', 'verbose_name_plural': 'Clientes / Empresas'},
        ),
        migrations.AddField(
            model_name='cliente',
            name='duracion_sesion_base',
            field=models.PositiveIntegerField(choices=[(3, '3 Horas'), (5, '5 Horas'), (8, '8 Horas')], default=8, verbose_name='Duración de Sesión de Estrategia'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ofrece_drone',
            field=models.BooleanField(default=False, verbose_name='¿Ofrece servicio de Drone?'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='permitir_dividir_sesion',
            field=models.BooleanField(default=True, verbose_name='¿Permitir dividir sesión? (4h + 4h)'),
        ),
    ]
