# Generated by Django 6.0.1 on 2026-01-27 21:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_reserva'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['-fecha_inicio'], 'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='detalle',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='email_contacto',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='servicio',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='tipo',
        ),
        migrations.AddField(
            model_name='reserva',
            name='creado_el',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='email',
            field=models.EmailField(default='info@agencia.com', max_length=254, verbose_name='Correo Electrónico'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='google_event_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='nombre_empresa',
            field=models.CharField(default='Empresa Genérica', max_length=100, verbose_name='Nombre de la Empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='notas',
            field=models.TextField(blank=True, null=True, verbose_name='Notas adicionales'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='sincronizado_google',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reserva',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_fin',
            field=models.DateTimeField(verbose_name='Fecha y Hora de Fin'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_inicio',
            field=models.DateTimeField(verbose_name='Fecha y Hora de Inicio'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='nombre_contacto',
            field=models.CharField(max_length=100, verbose_name='Persona de Contacto'),
        ),
    ]
